# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-10-26 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_complaint', models.CharField(choices=[('WATER', 'water'), ('ELECTRIC', 'electric'), ('ROAD', 'road'), ('SEWAGE', 'sewage'), ('WASTE_COLLECTION', 'waste_collection'), ('OTHERS', 'others'), ('CLEANING', 'cleaning')], default='OTHERS', max_length=30)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('solved', models.CharField(choices=[('SOLVED', 'solved'), ('NOT SOLVED', 'unsolved'), ('UNDER CONSIDERATION', 'under consideration')], default='NOT SOLVED', max_length=50)),
                ('sub_muncipal_division', models.CharField(choices=[('A_ZONE', 'a_zone'), ('B_ZONE', 'b_zone'), ('C_ZONE', 'c_zone'), ('D_ZONE', 'd_zone')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('area', models.CharField(max_length=20)),
                ('complaint_desc', models.TextField()),
                ('address', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('tax_id_number', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
                ('address', models.CharField(max_length=1024)),
                ('area', models.CharField(max_length=512)),
                ('pin', models.IntegerField(max_length=6)),
                ('mobile', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
